### ISSUE TITLE
Prevent HTTP communication.

### ISSUE THREAD

**Issue by Anduin2017** [AiursoftWeb/AiurVersionControl#5]

**Comment by MESOLONELY** [comment]
Does this means change the http post request to websocket in UploadFromAsync?

**Comment by Anduin2017** [comment]
I think the best practice for the websocket remote is to use pure websocket. Like game.

Usually in games, there only maintain one connection and everything just sends through.

But in our case, this issue is still under consideration. Because it's hard for us to change. Once you use pure websocket, it's hard for you to pull. Because when you send pull, you expect the pull result. While the remote may send you new event.

It requires us carefully design it.
